[project]
name = "python-cookiecutter-uv"
version = "0.1.0"
description = "A Python cookiecutter template using uv for dependency management."
authors = [{ name = "Jordan Pinder", email = "Jordan.Pinder@communities.gov.uk" }]
readme = "README.md"
keywords = ["cookiecutter", "template", "uv", "python"]
requires-python = ">=3.12,<4.0"
dependencies = [
    "cookiecutter>=2.7.1",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Code Generators",
]

[project.urls]
Repository = "https://github.com/communitiesuk/python-cookiecutter-uv"
Documentation = "https://communitiesuk.github.io/python-cookiecutter-uv/"
Homepage = "https://communitiesuk.github.io/python-cookiecutter-uv/"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cookies>=0.7.0",
    "tox-uv>=1.33.4",
    "ruff>=0.15.7",
    "deptry>=0.25.1",
    "pyrefly>=0.61.0",
    "pre-commit>=4.5.1",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.6",
    "mkdocstrings[python]>=1.0.3",
    "pyyaml>=6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["python_cookiecutter_uv"]

[tool.pyrefly]
project-includes = ["python_cookiecutter_uv"]
python-version = "3.12"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
target-version = "py312"
line-length = 120
fix = true

[tool.ruff.lint]
select = [
    "YTT",
    "S",
    "B",
    "A",
    "C4",
    "T10",
    "SIM",
    "I",
    "C90",
    "E", "W",
    "F",
    "PGH",
    "UP",
    "RUF",
    "TRY",
]
ignore = [
    "E501",
    "E731",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101", "S603"]

[tool.deptry]
extend_exclude = ["\\{\\{.*"]

[tool.deptry.per_rule_ignores]
DEP002 = ["cookiecutter"]
