[project]
name = "{{cookiecutter.__clean_slug}}"
version = "0.0.1"
description = "{{cookiecutter.project_description}}"
authors = [
    { name = "{{cookiecutter.author_name}}", email = "{{cookiecutter.author_email}}" },
]
readme = "README.md"
license = { file = "LICENCE" }
keywords = ["python"]
requires-python = ">=3.12,<3.14"
classifiers = [
    "{{cookiecutter.development_status}}",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

dependencies = []

[dependency-groups]
dev = [
    {%- if cookiecutter.typechecker == 'ty' %}
    "ty>=0.0.1a11",
    {% else %}
    "mypy >=1.16.1",
    {%- endif %}
    {%- if cookiecutter.include_unit_testing == 'y' %}
    "pytest>=7.2.0",
    "pytest-cov>=4.0.0",
    "coverage>=7.8.2",
    {%- endif %}
    {%- if cookiecutter.include_docs == 'y' %}
    "portray>=1.8.0",
    "legacy-cgi>=2.6.3",
    "setuptools>=80.9.0",
    {%- endif %}
    {%- if cookiecutter.include_nox == 'y' %}
    "nox>=2025.5.1",
    {%- endif %}
    "pre-commit>=4.2.0",
    "ruff>=0.12.0",
]

[project.urls]
homepage = "https://github.com/{{cookiecutter.repository_home}}/{{cookiecutter.repository_name}}"
repository = "https://github.com/{{cookiecutter.repository_home}}/{{cookiecutter.repository_name}}.git"
{%- if cookiecutter.include_docs == 'y' %}
documentation = "https://github.com/{{cookiecutter.repository_home}}.github.io/{{cookiecutter.repository_name}}"
{%- else %}
documentation = "https://github.com/{{cookiecutter.repository_home}}/{{cookiecutter.repository_name}}"
{%- endif %}
issues = "https://github.com/{{cookiecutter.repository_home}}/{{cookiecutter.repository_name}}/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["{{cookiecutter.__clean_slug}}"]

{% if cookiecutter.typechecker == 'ty' %}
[tool.ty]
src.root = "./src"
environment.python = "./.venv"
terminal.output-format = "concise"
{%- else %}
[tool.mypy]
files = ["{{cookiecutter.__clean_slug}}",{% if cookiecutter.include_unit_testing == 'y' %} "tests"{%- endif %}]
{% if cookiecutter.include_nox == 'y' %}
exclude = "noxfile.py"
{%- endif %}
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_any_unimported = false
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = false
warn_unused_ignores = true
show_error_codes = true
{%- endif %}

[tool.ruff]
src = ["{{cookiecutter.__clean_slug}}",{% if cookiecutter.include_unit_testing == 'y' %} "tests"{%- endif %}]
line-length = 100
indent-width = 4

[tool.ruff.lint]
pydocstyle.convention = "google"
fixable = ["ALL"]
select = ["ALL"]
ignore = [
    "FA102",   # Flake8-future-annotations
    "F401",    # Disable fix for unused imports
    "B904",    # Allow raising exceptions without from e
    "PLR0913", # too many arguments
    "CPY",     # Flake8-copyright
    "T201",    # Debugging print statements
    "ERA",     # Eradicate – detects commented-out code
    "BLE001",  # Catch-all exceptions
    "D100",    # missing docstring in public module
    "D105",    # undocumented magic method
    "D107",    # undocumented public init
    "D203",    # incorrect-blank-line-before-class
    "D205",    # line-between-summary-and-description
    "D212",    # multi-line-summary-first-line
    "D400",    # missing-trailing-period
    "D407",    # missing-dashed-underline-after-section
    "S311",    # rand-usage
]

{% if cookiecutter.include_unit_testing == "y" -%}
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"

[tool.coverage.paths]
source = ["{{cookiecutter.__clean_slug}}"]
tests = ["tests", "*/tests"]

[tool.coverage.report]
skip_empty = true
show_missing = true
fail_under = 100

[tool.coverage.run]
branch = true
source = ["{{cookiecutter.__clean_slug}}"]
{%- endif %}
