[tox]
skipsdist = true
envlist = py312, py313, py314

[gh-actions]
python =
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
passenv = PYTHON_VERSION
allowlist_externals = uv
commands =
    uv sync --python {envpython}
    uv run python -m pytest tests {% if cookiecutter.codecov == "y" %}--cov --cov-config=pyproject.toml --cov-report=xml{% endif %}

    uv run {% if cookiecutter.typechecker == "mypy" %}mypy{% elif cookiecutter.typechecker == "ty" %}ty check{% else %}pyrefly check{% endif %}
