[project]
name = "{{ cookiecutter.project_slug }}"
version = "0.0.1"
description = "{{ cookiecutter.project_description }}"
authors = [{ name = "{{ cookiecutter.author_name }}", email = "{{ cookiecutter.author_email }}" }]
readme = "README.md"
keywords = ["python"]
requires-python = ">=3.12,<3.14"
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
Repository = "{{ cookiecutter.git_url }}"

[dependency-groups]
dev = [
    "pre-commit>=2.20.0",
    "nox>=2025.2.9",
    "mypy>=0.991",
    "ruff>=0.11.5",
    {% if cookiecutter.include_unit_testing == 'y' -%}
    "pytest>=7.2.0",
    "pytest-cov>=4.0.0",
    {%- endif %}
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["{{ cookiecutter.package_name }}"]

[tool.setuptools]
py-modules = ["{{cookiecutter.project_slug}}"]

[tool.mypy]
files = "{{ cookiecutter.project_slug }}"
exclude = "noxfile.py"
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true

[tool.ruff]
line-length = 88
fix = true

[tool.ruff.lint]
select = [
    "YTT", "S", "B", "A", "C4", "T10", "SIM",
    "I", "C90", "E", "W", "F", "PGH", "UP", "RUF", "TRY"
]
ignore = [
    "E501",  # LineTooLong
    "E731",  # DoNotAssignLambda
]

[tool.ruff.lint.per-file-ignores]
"noxfile.py" = ["D402"]
{% if cookiecutter.include_unit_testing == "y" -%}
"tests/*" = ["ARG", "S101", "SLF001"]
{%- endif %}

[tool.ruff.format]
preview = true

{% if cookiecutter.include_unit_testing == "y" -%}
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["{{ cookiecutter.package_name }}"]
{%- endif %}
